### ISSUE TITLE
Sytanx errors when there is single quotes in tip

### ISSUE THREAD

**Issue by Kamilcuk** [michaelb/vim-tips#12] opened 2020-10-09 13:08 UTC
:D  In my vimrc I have:
```
nnoremap <leader>fs :call MyCscope('s')<CR>
```
The `'s'` causes problems, because in `vim-tips.vim` the value is passed using literal-string:
```
vim.command("let s:tip = '%s'"%s)
````
The single quotes gets improperly closed and it results in some unreadable syntax errors. The following:

 ```diff
 s = tip()
-vim.command("let s:tip ='%s'"%s)
+s = s.replace("\\", "\\\\")
+s = s.replace("\"", "\\\"")
+vim.command("let s:tip = \"%s\"" % s)
```

I guess fixes it. Or I think alternatively something along `s.replace("'", "' . \"'\" . '")`

**Comment by michaelb** [comment] 2020-10-10 07:47
Thanks a lot!

I should have thought of that from the beginning, looks like I still have a lot to learn.
I was able to reproduce and fix with your first suggestion, which also encompasses double-quotes " and is what I should have done from the start.

This issue will be closed by the PR merging the changes to master

**Closed as completed** 2020-10-10 07:48 UTC
